# Generated by Django 6.0.1 on 2026-03-19 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('import_type', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('text', 'Text'), ('bool', 'Boolean')], max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_filterable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('doi__isnull', False), models.Q(('doi', ''), _negated=True)), fields=('doi',), name='study_unique_doi_when_present')],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('cohort', models.CharField(blank=True, max_length=255)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='database.study')),
            ],
            options={
                'ordering': ['study__title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('group_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='database.group')),
                ('group_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='database.group')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='database.study')),
            ],
            options={
                'ordering': ['study__title', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scientific_name', models.CharField(db_index=True, max_length=255)),
                ('rank', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ncbi_taxonomy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='database.taxon')),
            ],
            options={
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='QuantitativeFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_type', models.CharField(choices=[('relative_abundance', 'Relative abundance')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantitative_findings', to='database.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantitative_findings', to='database.importbatch')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantitative_findings', to='database.taxon')),
            ],
            options={
                'ordering': ['group__study__title', 'group__name', 'taxon__scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='QualitativeFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('enriched', 'Enriched'), ('depleted', 'Depleted'), ('increased', 'Increased'), ('decreased', 'Decreased')], max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_findings', to='database.comparison')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitative_findings', to='database.importbatch')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_findings', to='database.taxon')),
            ],
            options={
                'ordering': ['comparison__study__title', 'comparison__label', 'taxon__scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_descendants', to='database.taxon')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_ancestors', to='database.taxon')),
            ],
            options={
                'ordering': ['ancestor__scientific_name', 'depth', 'descendant__scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_class', models.CharField(choices=[('scientific', 'Scientific'), ('synonym', 'Synonym'), ('alias', 'Alias'), ('imported_as_written', 'Imported As Written')], max_length=50)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_preferred', models.BooleanField(default=False)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='database.taxon')),
            ],
            options={
                'ordering': ['name', 'taxon__scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='BetaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_metrics', to='database.comparison')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_metrics', to='database.importbatch')),
            ],
            options={
                'ordering': ['comparison__study__title', 'comparison__label', 'metric'],
                'constraints': [models.UniqueConstraint(fields=('comparison', 'metric', 'source'), name='beta_metric_unique_comparison_metric_source')],
            },
        ),
        migrations.CreateModel(
            name='AlphaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpha_metrics', to='database.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alpha_metrics', to='database.importbatch')),
            ],
            options={
                'ordering': ['group__study__title', 'group__name', 'metric'],
                'constraints': [models.UniqueConstraint(fields=('group', 'metric', 'source'), name='alpha_metric_unique_group_metric_source')],
            },
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='database.group')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='database.metadatavariable')),
            ],
            options={
                'ordering': ['group__study__title', 'group__name', 'variable__name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'variable'), name='metadata_value_unique_group_variable'), models.CheckConstraint(condition=models.Q(models.Q(('value_bool__isnull', True), ('value_float__isnull', False), ('value_int__isnull', True), ('value_text__isnull', True)), models.Q(('value_bool__isnull', True), ('value_float__isnull', True), ('value_int__isnull', False), ('value_text__isnull', True)), models.Q(('value_bool__isnull', True), ('value_float__isnull', True), ('value_int__isnull', True), ('value_text__isnull', False)), models.Q(('value_bool__isnull', False), ('value_float__isnull', True), ('value_int__isnull', True), ('value_text__isnull', True)), _connector='OR'), name='metadata_value_exactly_one_typed_value')],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('study', 'name'), name='group_unique_study_name'),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.UniqueConstraint(fields=('study', 'group_a', 'group_b', 'label'), name='comparison_unique_study_groups_label'),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.CheckConstraint(condition=models.Q(('group_a', models.F('group_b')), _negated=True), name='comparison_distinct_groups'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['rank', 'scientific_name'], name='taxon_rank_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxon',
            constraint=models.UniqueConstraint(condition=models.Q(('ncbi_taxonomy_id__isnull', False)), fields=('ncbi_taxonomy_id',), name='taxon_unique_ncbi_taxonomy_id_when_present'),
        ),
        migrations.AddConstraint(
            model_name='quantitativefinding',
            constraint=models.UniqueConstraint(fields=('group', 'taxon', 'value_type', 'source'), name='quantitative_finding_unique_group_taxon_type_source'),
        ),
        migrations.AddConstraint(
            model_name='qualitativefinding',
            constraint=models.UniqueConstraint(fields=('comparison', 'taxon', 'direction', 'source'), name='qualitative_finding_unique_comparison_taxon_direction_source'),
        ),
        migrations.AddIndex(
            model_name='taxonclosure',
            index=models.Index(fields=['ancestor', 'depth', 'descendant'], name='taxon_closure_anc_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonclosure',
            index=models.Index(fields=['descendant', 'depth', 'ancestor'], name='taxon_closure_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxonclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='taxon_closure_unique_ancestor_descendant'),
        ),
        migrations.AddConstraint(
            model_name='taxonclosure',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 0)), name='taxon_closure_depth_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='taxonname',
            index=models.Index(fields=['name_class', 'name'], name='taxon_name_class_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxonname',
            constraint=models.UniqueConstraint(fields=('taxon', 'name', 'name_class'), name='taxon_name_unique_taxon_name_class'),
        ),
    ]
