# Generated by Django 6.0.1 on 2026-03-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alpha_metrics', to='database.importbatch')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpha_metrics', to='database.sample')),
            ],
            options={
                'ordering': ['sample', 'metric_type'],
                'constraints': [models.UniqueConstraint(fields=('sample', 'metric_type'), name='alpha_metric_unique_sample_metric_type')],
            },
        ),
        migrations.CreateModel(
            name='BetaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_metrics', to='database.importbatch')),
                ('sample_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_metrics_as_first', to='database.sample')),
                ('sample_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_metrics_as_second', to='database.sample')),
            ],
            options={
                'ordering': ['sample_a', 'sample_b', 'metric_type'],
                'constraints': [models.UniqueConstraint(fields=('sample_a', 'sample_b', 'metric_type'), name='beta_metric_unique_sample_pair_metric_type'), models.CheckConstraint(condition=models.Q(('sample_a__lt', models.F('sample_b'))), name='beta_metric_canonical_sample_order')],
            },
        ),
    ]
